apiVersion: apps/v1
kind: Deployment
metadata:
  name: findyourhome-api-deployment
  labels:
    app: findyourhome-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: findyourhome-api
  template:
    metadata:
      labels: 
        app: findyourhome-api
    spec:
      containers:
        - name: findyourhome-api-containers
          image: graghu1/findyourhome_api_image
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              value: "abvd23232s"
            - name: DBURL
              value: ""
            - name: CLIENT_ORIGIN
              value: "http://localhost:5173"
              # value: "http://a5841a4ab14ed486e964d02de8d93bfd-1835817881.us-east-1.elb.amazonaws.com/"
            - name: ML_MODEL_URI
              value: ""