apiVersion: v1
kind : Service
metadata:
  name: findyourhome-client-service
spec:
  selector:
    app: findyourhome-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort